package com.yuyan.inputmethod.util

object LX17PinYinUtils {
    private val lx17KeyMap = mapOf(
        'b' to "b",
        'd' to "d",
        'u' to "d",
        'c' to "f",
        'f' to "f",
        'g' to "g",
        'h' to "h",
        'a' to "h",
        'p' to "h",
        'i' to "j",
        'j' to "j",
        'k' to "j",
        'l' to "l",
        'm' to "m",
        's' to "m",
        'n' to "n",
        'r' to "n",
        'q' to "q",
        't' to "t",
        'w' to "w",
        'z' to "w",
        'e' to "w",
        'x' to "x",
        'o' to "x",
        'v' to "x",
        'y' to "y",
    )

    private val lx17PinyinMap = HashMap<String, String>(225)

    init {
        lx17PinyinMap.put("h", "h,p")
        lx17PinyinMap.put("s", "sh")
        lx17PinyinMap.put("z", "zh")
        lx17PinyinMap.put("b", "b")
        lx17PinyinMap.put("x", "x")
        lx17PinyinMap.put("m", "m,s")
        lx17PinyinMap.put("l", "l")
        lx17PinyinMap.put("d", "d")
        lx17PinyinMap.put("y", "y")
        lx17PinyinMap.put("w", "w,z")
        lx17PinyinMap.put("j", "j,k")
        lx17PinyinMap.put("n", "n,r")
        lx17PinyinMap.put("c", "ch")
        lx17PinyinMap.put("q", "q,~")
        lx17PinyinMap.put("g", "g")
        lx17PinyinMap.put("f", "f,c")
        lx17PinyinMap.put("t", "t")

        lx17PinyinMap.put("hh", "ha,hua,pa")
        lx17PinyinMap.put("hs", "hen,pen")
        lx17PinyinMap.put("hz", "hang,pang,piao")
        lx17PinyinMap.put("hb", "hao,pao")
        lx17PinyinMap.put("hx", "huai,huan,po")
        lx17PinyinMap.put("hm", "pie,huo")
        lx17PinyinMap.put("hl", "hai,pai")
        lx17PinyinMap.put("hd", "hu,pu")
        lx17PinyinMap.put("hy", "heng,peng,ping")
        lx17PinyinMap.put("hw", "he")
        lx17PinyinMap.put("hj", "pi")
        lx17PinyinMap.put("hn", "han,pan")
        lx17PinyinMap.put("hc", "hui")
        lx17PinyinMap.put("hq", "huang,pian")
        lx17PinyinMap.put("hg", "hei,pei,hun")
        lx17PinyinMap.put("hf", "hiu,hou,pou")
        lx17PinyinMap.put("ht", "hong")

        lx17PinyinMap.put("sh", "sha,shua")
        lx17PinyinMap.put("ss", "shen")
        lx17PinyinMap.put("sz", "shang")
        lx17PinyinMap.put("sb", "shao")
        lx17PinyinMap.put("sx", "shuai,shuan")
        lx17PinyinMap.put("sm", "shuo")
        lx17PinyinMap.put("sl", "shai")
        lx17PinyinMap.put("sd", "shu")
        lx17PinyinMap.put("sy", "sheng")
        lx17PinyinMap.put("sw", "she")
        lx17PinyinMap.put("sj", "shi")
        lx17PinyinMap.put("sn", "shan")
        lx17PinyinMap.put("sc", "shui")
        lx17PinyinMap.put("sq", "shuang")
        lx17PinyinMap.put("sg", "shun,shei")
        lx17PinyinMap.put("sf", "shou")

        lx17PinyinMap.put("zh", "zha,zhua")
        lx17PinyinMap.put("zs", "zhen")
        lx17PinyinMap.put("zz", "zhang")
        lx17PinyinMap.put("zb", "zhao")
        lx17PinyinMap.put("zx", "zhuai,zhuan")
        lx17PinyinMap.put("zm", "zhuo")
        lx17PinyinMap.put("zl", "zhai")
        lx17PinyinMap.put("zd", "zhu")
        lx17PinyinMap.put("zy", "zheng")
        lx17PinyinMap.put("zw", "zhe")
        lx17PinyinMap.put("zj", "zhi")
        lx17PinyinMap.put("zn", "zhan")
        lx17PinyinMap.put("zc", "zhui")
        lx17PinyinMap.put("zq", "zhuang")
        lx17PinyinMap.put("zg", "zhun")
        lx17PinyinMap.put("zf", "zhou")
        lx17PinyinMap.put("zt", "zhong")

        lx17PinyinMap.put("bh", "ba")
        lx17PinyinMap.put("bs", "ben")
        lx17PinyinMap.put("bz", "bang,biao")
        lx17PinyinMap.put("bb", "bao")
        lx17PinyinMap.put("bx", "bo")
        lx17PinyinMap.put("bm", "bie")
        lx17PinyinMap.put("bl", "bai")
        lx17PinyinMap.put("bd", "bu")
        lx17PinyinMap.put("by", "beng,bing")
        lx17PinyinMap.put("bj", "bi")
        lx17PinyinMap.put("bn", "ban")
        lx17PinyinMap.put("bc", "biang")
        lx17PinyinMap.put("bq", "bian")
        lx17PinyinMap.put("bg", "bei")

        lx17PinyinMap.put("xh", "xia")
        lx17PinyinMap.put("xs", "xin")
        lx17PinyinMap.put("xz", "xiao")
        lx17PinyinMap.put("xb", "xiong")
        lx17PinyinMap.put("xx", "xuan")
        lx17PinyinMap.put("xm", "xie")
        lx17PinyinMap.put("xl", "xue")
        lx17PinyinMap.put("xd", "xu")
        lx17PinyinMap.put("xy", "xing")
        lx17PinyinMap.put("xj", "xi")
        lx17PinyinMap.put("xn", "xiang")
        lx17PinyinMap.put("xc", "xian")
        lx17PinyinMap.put("xq", "xun")
        lx17PinyinMap.put("xg", "xun")
        lx17PinyinMap.put("xf", "xiu")

        lx17PinyinMap.put("mh", "ma")
        lx17PinyinMap.put("ms", "men,sen,min")
        lx17PinyinMap.put("mz", "mang,sang,miao")
        lx17PinyinMap.put("mb", "mao,sao")
        lx17PinyinMap.put("mx", "mo,suan")
        lx17PinyinMap.put("mm", "mie,muo,suo")
        lx17PinyinMap.put("ml", "mai,sai")
        lx17PinyinMap.put("md", "mu,su")
        lx17PinyinMap.put("my", "ming,meng,seng")
        lx17PinyinMap.put("mw", "se")
        lx17PinyinMap.put("mj", "mi")
        lx17PinyinMap.put("mn", "man,san")
        lx17PinyinMap.put("mc", "sui")
        lx17PinyinMap.put("mq", "mian")
        lx17PinyinMap.put("mg", "mei,sun")
        lx17PinyinMap.put("mf", "sui,mou,sou")
        lx17PinyinMap.put("mt", "song")

        lx17PinyinMap.put("lh", "la,lia")
        lx17PinyinMap.put("ls", "lin")
        lx17PinyinMap.put("lz", "lang,liao")
        lx17PinyinMap.put("lb", "lao")
        lx17PinyinMap.put("lx", "luan")
        lx17PinyinMap.put("lm", "lie,luo")
        lx17PinyinMap.put("ll", "lai,lue")
        lx17PinyinMap.put("ld", "lu")
        lx17PinyinMap.put("ly", "leng,ling")
        lx17PinyinMap.put("lw", "le")
        lx17PinyinMap.put("lj", "li")
        lx17PinyinMap.put("ln", "lan")
        lx17PinyinMap.put("lc", "liang")
        lx17PinyinMap.put("lq", "lian")
        lx17PinyinMap.put("lg", "lei,lun")
        lx17PinyinMap.put("lf", "liu,lou")
        lx17PinyinMap.put("lt", "long")

        lx17PinyinMap.put("dh", "da")
        lx17PinyinMap.put("ds", "den")
        lx17PinyinMap.put("dz", "dang,diao")
        lx17PinyinMap.put("db", "dao")
        lx17PinyinMap.put("dx", "duan")
        lx17PinyinMap.put("dm", "die,duo")
        lx17PinyinMap.put("dl", "dai")
        lx17PinyinMap.put("dd", "du")
        lx17PinyinMap.put("dy", "deng,ding")
        lx17PinyinMap.put("dw", "de")
        lx17PinyinMap.put("dj", "di")
        lx17PinyinMap.put("dn", "dan")
        lx17PinyinMap.put("dc", "dui")
        lx17PinyinMap.put("dq", "dian,duang")
        lx17PinyinMap.put("dg", "dun")
        lx17PinyinMap.put("df", "diu,dou")
        lx17PinyinMap.put("dt", "dong")

        lx17PinyinMap.put("yh", "ya")
        lx17PinyinMap.put("ys", "yin")
        lx17PinyinMap.put("yz", "yang")
        lx17PinyinMap.put("yb", "yao")
        lx17PinyinMap.put("yx", "yuan")
        lx17PinyinMap.put("yl", "yue")
        lx17PinyinMap.put("yd", "yu")
        lx17PinyinMap.put("yy", "ying")
        lx17PinyinMap.put("yw", "ye")
        lx17PinyinMap.put("yj", "yi")
        lx17PinyinMap.put("yn", "yan")
        lx17PinyinMap.put("yg", "yun")
        lx17PinyinMap.put("yf", "you")
        lx17PinyinMap.put("yt", "yong")

        lx17PinyinMap.put("wh", "wa,za")
        lx17PinyinMap.put("ws", "wen,zen")
        lx17PinyinMap.put("wz", "wang,zang")
        lx17PinyinMap.put("wb", "zao")
        lx17PinyinMap.put("wx", "zuan")
        lx17PinyinMap.put("wm", "zuo")
        lx17PinyinMap.put("wl", "zai,wai")
        lx17PinyinMap.put("wd", "zu,wu")
        lx17PinyinMap.put("wy", "zeng,weng")
        lx17PinyinMap.put("ww", "ze")
        lx17PinyinMap.put("wj", "zi")
        lx17PinyinMap.put("wn", "zan,wan")
        lx17PinyinMap.put("wc", "zui")
        lx17PinyinMap.put("wq", "")
        lx17PinyinMap.put("wg", "zei,wei,zun")
        lx17PinyinMap.put("wf", "zou")
        lx17PinyinMap.put("wt", "zong")

        lx17PinyinMap.put("jh", "ja,ka,jia,kua")
        lx17PinyinMap.put("js", "ken,jin")
        lx17PinyinMap.put("jz", "kang,jiao")
        lx17PinyinMap.put("jb", "jao,kao,jiong")
        lx17PinyinMap.put("jx", "kuai,juan,kuan")
        lx17PinyinMap.put("jm", "jie,kuo")
        lx17PinyinMap.put("jl", "kai,jue")
        lx17PinyinMap.put("jd", "ju, ku")
        lx17PinyinMap.put("jy", "keng,jing")
        lx17PinyinMap.put("jw", "ke")
        lx17PinyinMap.put("jj", "ji")
        lx17PinyinMap.put("jn", "kan")
        lx17PinyinMap.put("jc", "jiang,kui")
        lx17PinyinMap.put("jq", "jian,kuang")
        lx17PinyinMap.put("jg", "jun,kun")
        lx17PinyinMap.put("jf", "jiu,kou")
        lx17PinyinMap.put("jt", "kong")

        lx17PinyinMap.put("nh", "na")
        lx17PinyinMap.put("ns", "nen,ren,nin")
        lx17PinyinMap.put("nz", "nang,rang,niao")
        lx17PinyinMap.put("nb", "nao,rao")
        lx17PinyinMap.put("nx", "nv,ruan")
        lx17PinyinMap.put("nm", "nie,ruo,nuo")
        lx17PinyinMap.put("nl", "nai,nue")
        lx17PinyinMap.put("nd", "ru,nu")
        lx17PinyinMap.put("ny", "reng,neng,ning")
        lx17PinyinMap.put("nw", "ne,re")
        lx17PinyinMap.put("nj", "ni,ri")
        lx17PinyinMap.put("nn", "nan,ran")
        lx17PinyinMap.put("nc", "niang,rui")
        lx17PinyinMap.put("nq", "nian")
        lx17PinyinMap.put("ng", "nei,run")
        lx17PinyinMap.put("nf", "niu,rou")
        lx17PinyinMap.put("nt", "nong,rong")

        lx17PinyinMap.put("ch", "cha,chua")
        lx17PinyinMap.put("cs", "chen")
        lx17PinyinMap.put("cz", "chang")
        lx17PinyinMap.put("cb", "chao")
        lx17PinyinMap.put("cx", "chuai,chuan")
        lx17PinyinMap.put("cm", "chuo")
        lx17PinyinMap.put("cl", "chai")
        lx17PinyinMap.put("cd", "chu")
        lx17PinyinMap.put("cy", "cheng")
        lx17PinyinMap.put("cw", "che")
        lx17PinyinMap.put("cj", "chi")
        lx17PinyinMap.put("cn", "chan")
        lx17PinyinMap.put("cc", "chui")
        lx17PinyinMap.put("cq", "chuang")
        lx17PinyinMap.put("cg", "chun")
        lx17PinyinMap.put("cf", "chou")
        lx17PinyinMap.put("ct", "chong")

        lx17PinyinMap.put("qh", "a,qia")
        lx17PinyinMap.put("qs", "en,qin")
        lx17PinyinMap.put("qz", "ang,qiao")
        lx17PinyinMap.put("qb", "ao,qiong")
        lx17PinyinMap.put("qx", "o,quan")
        lx17PinyinMap.put("qm", "qie")
        lx17PinyinMap.put("ql", "ai,que")
        lx17PinyinMap.put("qd", "qu")
        lx17PinyinMap.put("qy", "eng,qing")
        lx17PinyinMap.put("qw", "e")
        lx17PinyinMap.put("qj", "qi")
        lx17PinyinMap.put("qn", "an")
        lx17PinyinMap.put("qc", "qiang")
        lx17PinyinMap.put("qq", "qian")
        lx17PinyinMap.put("qg", "qun")
        lx17PinyinMap.put("qf", "qiu")
        lx17PinyinMap.put("qt", "er,qong")

        lx17PinyinMap.put("gh", "ga,gua")
        lx17PinyinMap.put("gs", "gen")
        lx17PinyinMap.put("gz", "gang")
        lx17PinyinMap.put("gb", "gao")
        lx17PinyinMap.put("gx", "guai,guan")
        lx17PinyinMap.put("gm", "guo")
        lx17PinyinMap.put("gl", "gai")
        lx17PinyinMap.put("gd", "gu")
        lx17PinyinMap.put("gy", "geng")
        lx17PinyinMap.put("gw", "ge")
        lx17PinyinMap.put("gn", "gan")
        lx17PinyinMap.put("gc", "gui")
        lx17PinyinMap.put("gq", "guang")
        lx17PinyinMap.put("gg", "gei,gun")
        lx17PinyinMap.put("gf", "gou")
        lx17PinyinMap.put("gt", "gong")

        lx17PinyinMap.put("fh", "fa,ca")
        lx17PinyinMap.put("fs", "fen,cen")
        lx17PinyinMap.put("fz", "fang,cang")
        lx17PinyinMap.put("fb", "cao")
        lx17PinyinMap.put("fx", "fo,cuan")
        lx17PinyinMap.put("fm", "fuo,cuo")
        lx17PinyinMap.put("fl", "cai")
        lx17PinyinMap.put("fd", "fu,cu")
        lx17PinyinMap.put("fy", "feng,ceng")
        lx17PinyinMap.put("fw", "ce")
        lx17PinyinMap.put("fj", "ci")
        lx17PinyinMap.put("fn", "fan,can")
        lx17PinyinMap.put("fc", "cui")
        lx17PinyinMap.put("fg", "fei,cun")
        lx17PinyinMap.put("ff", "fou,cou")
        lx17PinyinMap.put("ft", "cong")

        lx17PinyinMap.put("th", "ta")
        lx17PinyinMap.put("tz", "tang,tiao")
        lx17PinyinMap.put("tb", "tao")
        lx17PinyinMap.put("tx", "tuan")
        lx17PinyinMap.put("tm", "tie,tuo")
        lx17PinyinMap.put("tl", "tai")
        lx17PinyinMap.put("td", "tu")
        lx17PinyinMap.put("ty", "teng,ting")
        lx17PinyinMap.put("tw", "te")
        lx17PinyinMap.put("tj", "ti")
        lx17PinyinMap.put("tn", "tan")
        lx17PinyinMap.put("tc", "tui")
        lx17PinyinMap.put("tq", "tian")
        lx17PinyinMap.put("tg", "tun")
        lx17PinyinMap.put("tf", "tou")
        lx17PinyinMap.put("tt", "tong")
    }

    /**
     * 获取键码对应的拼音组合
     */
    fun lx17KeyToPinyin(sequence: String?): Array<String> {
        if (sequence.isNullOrEmpty()) {
            return emptyArray()
        }
        val sequenceString = if (sequence.length > 2) sequence.substring(0..1) else sequence
        val pinyin = ArrayList<String>(5)
        for (length in sequenceString.length downTo 1) {
            val prefix = sequenceString.substring(0, length)
            lx17PinyinMap[prefix]?.let { value ->
                pinyin.add(value)
            }
        }
        return pinyin.joinToString(",") { it }.split(",").toTypedArray()
    }

    fun pinyin2Lx17Key(pinyin: Char): String = lx17KeyMap[pinyin]?:pinyin.toString()
}