
package com.yuyan.imemodule.view.keyboard

import com.yuyan.imemodule.manager.InputModeSwitcherManager

val qwertyKeyPreset: Map<Int, Array<String>> = hashMapOf(
    45 to arrayOf("Q", "["),
    51 to arrayOf("W", "]"),
    33 to arrayOf("E", "<"),
    46 to arrayOf("R", ">"),
    48 to arrayOf("T", "("),
    53 to arrayOf("Y", ")"),
    49 to arrayOf("U", "{"),
    37 to arrayOf("I", "}"),
    43 to arrayOf("O", "|"),
    44 to arrayOf("P", "-"),
    29 to arrayOf("A", "､"),
    47 to arrayOf("S", "/"),
    32 to arrayOf("D", ":"),
    34 to arrayOf("F", ";"),
    35 to arrayOf("G", "_"),
    36 to arrayOf("H", "#"),
    38 to arrayOf("J", "~"),
    39 to arrayOf("K", "'"),
    40 to arrayOf("L", "\""),
    75 to arrayOf("分词"),
    54 to arrayOf("Z", "@"),
    52 to arrayOf("X", ","),
    31 to arrayOf("C", "."),
    50 to arrayOf("V", "&"),
    30 to arrayOf("B", "?"),
    42 to arrayOf("N", "!"),
    41 to arrayOf("M", "..."),
    InputModeSwitcherManager.USER_DEF_KEYCODE_SYMBOL_3 to arrayOf("符号"),
    InputModeSwitcherManager.USER_DEF_KEYCODE_NUMBER_5 to arrayOf("123"),
    InputModeSwitcherManager.USER_DEF_KEYCODE_EMOJI_4 to arrayOf("表情"),
)

val qwertyPYKeyPreset: Map<Int, Array<String>> = hashMapOf(
    45 to arrayOf("Q", "["),
    51 to arrayOf("W", "]"),
    33 to arrayOf("E", "<"),
    46 to arrayOf("R", ">"),
    48 to arrayOf("T", "("),
    53 to arrayOf("Y", ")"),
    49 to arrayOf("U", "{"),
    37 to arrayOf("I", "}"),
    43 to arrayOf("O", "|"),
    44 to arrayOf("P", "-"),
    29 to arrayOf("A", "､"),
    47 to arrayOf("S", "/"),
    32 to arrayOf("D", ":"),
    34 to arrayOf("F", ";"),
    35 to arrayOf("G", "_"),
    36 to arrayOf("H", "#"),
    38 to arrayOf("J", "~"),
    39 to arrayOf("K", "‘"),
    40 to arrayOf("L", "\""),
    75 to arrayOf("分词"),
    54 to arrayOf("Z", "@"),
    52 to arrayOf("X", ","),
    31 to arrayOf("C", "｡"),
    50 to arrayOf("V", "&"),
    30 to arrayOf("B", "?"),
    42 to arrayOf("N", "!"),
    41 to arrayOf("M", "..."),
    InputModeSwitcherManager.USER_DEF_KEYCODE_SYMBOL_3 to arrayOf("符号"),
    InputModeSwitcherManager.USER_DEF_KEYCODE_NUMBER_5 to arrayOf("123"),
    InputModeSwitcherManager.USER_DEF_KEYCODE_EMOJI_4 to arrayOf("表情"),
)

val doubleFlyPYKeyPreset: Map<Int, Array<String>> = hashMapOf(
    45 to arrayOf("Q", "[", "iu"),
    51 to arrayOf("W", "]", "ei"),
    33 to arrayOf("E", "<", "e"),
    46 to arrayOf("R", ">", "uan"),
    48 to arrayOf("T", "（", "ue ve"),
    53 to arrayOf("Y", "）", "un"),
    49 to arrayOf("U", "{", "sh"),
    37 to arrayOf("I", "}", "ch"),
    43 to arrayOf("O", "|", "uo"),
    44 to arrayOf("P", "-", "ie"),
    29 to arrayOf("A", "-", "a"),
    47 to arrayOf("S", "/", "iong ong"),
    32 to arrayOf("D", ":", "ai"),
    34 to arrayOf("F", ";", "en"),
    35 to arrayOf("G", "_", "eng"),
    36 to arrayOf("H", "#", "ang"),
    38 to arrayOf("J", "~", "an"),
    39 to arrayOf("K", "'", "ing uai"),
    40 to arrayOf("L", "\"", "iang uang"),
    75 to arrayOf("分词"),
    54 to arrayOf("Z", "@", "ou"),
    52 to arrayOf("X", ",", "ia ua"),
    31 to arrayOf("C", ".", "ao"),
    50 to arrayOf("V", "&", "ui zh"),
    30 to arrayOf("B", "?", "in"),
    42 to arrayOf("N", "!", "iao"),
    41 to arrayOf("M", "...", "ian"),
    InputModeSwitcherManager.USER_DEF_KEYCODE_SYMBOL_3 to arrayOf("符号"),
    InputModeSwitcherManager.USER_DEF_KEYCODE_NUMBER_5 to arrayOf("123"),
    InputModeSwitcherManager.USER_DEF_KEYCODE_EMOJI_4 to arrayOf("表情"),
)

val lx17PYKeyPreset: Map<Int, Array<String>> = hashMapOf(
    36 to arrayOf( "HP", "-", "a ia ua"),
    47 to arrayOf("Sh", "/", "en in"),
    54 to arrayOf("Zh", ";", "ang iao"),
    30 to arrayOf("B", "?", "ao iong"),
    52 to arrayOf("oXv", "#", "uai uan"),
    41 to arrayOf("MS", "~", "ie uo"),
    40 to arrayOf("L", "\"", "ai ue"),
    32 to arrayOf("D", ":", "u"),
    53 to arrayOf("Y", ")", "eng ing"),
    51 to arrayOf("WZ", "@", "e"),
    38 to arrayOf("JK", "&", "i"),
    42 to arrayOf("NR", "!", "an"),
    31 to arrayOf("Ch", "，", "iang ui"),
    45 to arrayOf("Q~", "。", "ian uang"),
    35 to arrayOf("G", "_", "ei un"),
    34 to arrayOf("FC", "…", "iu ou"),
    48 to arrayOf("T", "(", "er ong"),
    InputModeSwitcherManager.USER_DEF_KEYCODE_SYMBOL_3 to arrayOf("符号"),
    InputModeSwitcherManager.USER_DEF_KEYCODE_NUMBER_5 to arrayOf("123"),
    InputModeSwitcherManager.USER_DEF_KEYCODE_EMOJI_4 to arrayOf("表情"),
)

val t9PYKeyPreset: Map<Int, Array<String>> = hashMapOf(
    7 to arrayOf("0"),  // 数字键盘使用
    9 to arrayOf("ABC", "2"),
    10 to arrayOf("DEF", "3"),
    11 to arrayOf("GHI", "4"),
    12 to arrayOf("JKL", "5"),
    13 to arrayOf("MNO", "6"),
    14 to arrayOf("PQRS", "7"),
    15 to arrayOf("TUV", "8"),
    16 to arrayOf("WXYZ", "9"),
    28 to arrayOf("重输"),
    75 to arrayOf("分词", "1"),
    77 to arrayOf("@"),
    InputModeSwitcherManager.USER_DEF_KEYCODE_SYMBOL_3 to arrayOf("符号"),
    InputModeSwitcherManager.USER_DEF_KEYCODE_NUMBER_5 to arrayOf("123"),
    InputModeSwitcherManager.USER_DEF_KEYCODE_RETURN_6 to arrayOf("返回"),
    InputModeSwitcherManager.USER_DEF_KEYCODE_EMOJI_4 to arrayOf("表情"),
)

val t9NumberKeyPreset: Map<Int, Array<String>> = hashMapOf(
    7 to arrayOf("0"),
    8 to arrayOf("1"),
    9 to arrayOf("2"),
    10 to arrayOf("3"),
    11 to arrayOf("4"),
    12 to arrayOf("5"),
    13 to arrayOf("6"),
    14 to arrayOf("7"),
    15 to arrayOf("8"),
    16 to arrayOf("9"),
    77 to arrayOf("@"),
    0 to arrayOf("."),
)