package com.yuyan.imemodule.keyboard

val doubleFlyMnemonicPreset: Map<Int, String> = hashMapOf(
    45 to "iu",
    51 to "ei",
    46 to "uan van",
    48 to "ue ve",
    53 to "un vn",
    49 to "sh",
    37 to "ch",
    43 to "uo",
    44 to "ie",
    47 to "iong ong",
    32 to "ai",
    34 to "en",
    35 to "eng",
    36 to "ang",
    38 to "an",
    39 to "ing uai",
    40 to "iang uang",
    75 to "分词",
    54 to "ou",
    52 to "ia ua",
    31 to "ao",
    50 to "ui zh",
    30 to "in",
    42 to "iao",
    41 to "ian",
)

val doubleNaturalMnemonicPreset: Map<Int, String> = hashMapOf(
    45 to "iu",
    51 to "ia ua",
    46 to "uan van",
    48 to "ue ve",
    53 to "uai ing",
    49 to "sh",
    37 to "ch",
    43 to "uo",
    44 to "un vn",
    47 to "iong ong",
    32 to "iang uang",
    34 to "en",
    35 to "eng",
    36 to "ang",
    38 to "an",
    39 to "ao",
    40 to "ai",
    75 to "分词",
    54 to "ei",
    52 to "ie",
    31 to "iao",
    50 to "ui zh",
    30 to "ou",
    42 to "in",
    41 to "ian",
)

val doubleAbcMnemonicPreset: Map<Int, String> = hashMapOf(
    45 to "ei",
    51 to "ian",
    33 to "ch",
    46 to "iu er",
    48 to "iang uang",
    53 to "ing",
    43 to "uo",
    44 to "uan",
    29 to "zh",
    47 to "iong ong",
    32 to "ia ua",
    34 to "en",
    35 to "eng",
    36 to "ang",
    38 to "an",
    39 to "ao",
    40 to "ai",
    75 to "分词",
    54 to "iao",
    52 to "ie",
    31 to "in uai",
    50 to "ve sh",
    30 to "ou",
    42 to "un",
    41 to "ue ui",
)

val doubleZiguangMnemonicPreset: Map<Int, String> = hashMapOf(
    45 to "ao",
    51 to "en",
    46 to "an",
    48 to "eng",
    53 to "in uai",
    49 to "zh",
    37 to "sh",
    43 to "uo",
    44 to "ai",
    29 to "ch",
    47 to "ang",
    32 to "ie",
    34 to "ian",
    35 to "iang uang",
    36 to "ong iong",
    38 to "iu er",
    39 to "ei",
    40 to "uan",
    54 to "ou",
    52 to "ia ua",
    30 to "iao",
    42 to "ui ve ue",
    41 to "un",
)

val doubleMSMnemonicPreset: Map<Int, String> = hashMapOf(
    45 to "iu",
    51 to "ia ua",
    46 to "uan er",
    48 to "ue",
    53 to "uai v",
    49 to "sh",
    37 to "ch",
    43 to "uo",
    44 to "un",
    47 to "ong iong",
    32 to "iang uang",
    34 to "en",
    35 to "eng",
    36 to "ang",
    38 to "an",
    39 to "ao",
    40 to "ai",
    54 to "ei",
    52 to "ie",
    31 to "iao",
    50 to "ve ui zh",
    30 to "ou",
    42 to "in",
    41 to "ian",
)

val doubleSogouMnemonicPreset: Map<Int, String> = hashMapOf(
    45 to "iu",
    51 to "ia ua",
    46 to "uan er",
    48 to "ue ve",
    53 to "uai v",
    49 to "sh",
    37 to "ch",
    43 to "uo",
    44 to "un",
    47 to "ong iong",
    32 to "iang uang",
    34 to "en",
    35 to "eng",
    36 to "ang",
    38 to "an",
    39 to "ao",
    40 to "ai",
    54 to "ei",
    52 to "ie",
    31 to "iao",
    50 to "ui zh",
    30 to "ou",
    42 to "in",
    41 to "ian",
)

val lx17MnemonicPreset: Map<Int, String> = hashMapOf(
    36 to "a ia ua",
    47 to "en in",
    54 to "ang iao",
    30 to "ao iong",
    52 to "uai uan",
    41 to "ie uo",
    40 to "ai ue",
    32 to "u",
    53 to "eng ing",
    51 to "e",
    38 to "i",
    42 to "an",
    31 to "iang ui",
    45 to "ian uang",
    35 to "ei un",
    34 to "iu ou",
    48 to "er ong",
)